image:
  file: .gitpod.Dockerfile

# Use 'lock file' to delay running ddev until it is installed
# https://www.gitpod.io/blog/gitpodify/#running-init-scripts
tasks:
  # - name: ddev_install
  #   init: |
  #     touch /tmp/.ddev-lock
  #     brew tap drud/ddev && brew install ddev
  #     rm /tmp/.ddev-lock
  - name: docker_up
    init: sudo docker-up
  - name: ddev_pull
    init: |
      docker pull drud/ddev-dbserver-mariadb-10.2:v1.16.0
      docker pull phpmyadmin:5
      docker pull drud/ddev-ssh-agent:v1.16.0
      docker pull drud/ddev-router:v1.16.2
      docker pull drud/ddev-webserver:v1.16.3
  - name: ddev_run
    # init: sleep 1 && while [ -f /tmp/.ddev-lock ]; do sleep 1; done
    command: |
      sleep 5
      mkcert -install
      ddev config global --instrumentation-opt-in=true
      ddev start

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
