image:
  file: .gitpod.Dockerfile

# First terminal runs `sudo docker-up`, second terminal runs a command with healthcheck, which generates the following error:
# WARN[2021-01-12T04:45:28.173819507Z] Health check for container a4aa03376287804e45ddad2bf4f7609cb1a113a9fc41ed9a344cebbe5ffc4809 error: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown
tasks:
  - name: docker_up
    command: sudo docker-up
  - name: run_command
    command: docker run -it --rm --health-cmd=ls --health-interval=1s debian:buster-slim bash

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
